Docs: JSONata refresh and update with new examples
zachowj/node-red-contrib-home-assistant-websocket pull request #1286
Opened 2024-01-30 10:40 UTC by oatybiscuit

Following your message last November, here is my submission:
[Do you have any interest in writing a JSONata guide geared toward using it with Home Assistant?](https://community.home-assistant.io/t/node-red-passing-variables-into-call-service-node/617410/7?u=biscuit)

Refresh JSONata material in the documentation.
Updated the Guide page with table to cross reference JSONata use to Nodes to Examples
Added JSONata 'primer' guide page
Reorganised JSONata examples to focus on node and use-type
Refresh existing examples and added new ones, with additional explanation on how to use JSONata specifically at each point.

All documentation is my own original work and I have not used any AI, only cross referencing back to the WebSocket documentation and the JSONata documentation.

All examples have been fully tested (in my environment) and the code checked.
All links updated and checked as far as I am able to.
New pages have been added to the vue-doc configuration (but have not been fully tested).

Unfortunately I live in the UK, and am currently on GMT which is the same as UTC so I am unable to double check any issues that may arise from the use of sensor.time_utc or sensor.time in regard to other sensor timestamps (local - UTC issues).

2024-02-01 16:37 UTC, zachowj commented
Wow, very nice.

2024-02-05 01:09 UTC, zachowj requested changes
Not sure if you were able to set up a local environment to test with but I just added [documentation](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/documentation.html) on how to do this.

2024-02-05 01:09 UTC, zachowj commented on docs/guide/jsonata-primer.md
> +    )
```suggestion
   ```jsonata
    (
      $object:={"first": 1, "second": 2, "third": 3};
      $replaceKey:= "second";
      $replaceVal:= 15;
      $spread($object) ~> $append({$replaceKey: $replaceVal}) ~> $merge()
    )
    ```
```

2024-02-05 01:09 UTC, zachowj commented on docs/guide/jsonata-primer.md
> +    )
```suggestion
    ```jsonata
    (
      $array:=[1, 2, 3, 4, 5, 6];
      $newval:=10;
      $index:=2;
      $append($array[[0..$index-1]], $newval)~>$append($array[[$index+1..$count($array)]])
    )
    ```
```

2024-02-05 01:09 UTC, zachowj commented on docs/cookbook/jsonata-1-call-service.md
> +- Mustache templates are delimited with '{{msg.payload}}'. Although acceptable in most JSON input fields, this is _invalid syntax_ in JSONata expressions and must not be used.
```suggestion
- Mustache templates are delimited with <code v-pre>{{msg.payload}}</code>. Although acceptable in most JSON input fields, this is _invalid syntax_ in JSONata expressions and must not be used.
```

2024-02-05 12:42 UTC, oatybiscuit commented
> Not sure if you were able to set up a local environment to test with but I just added [documentation](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/documentation.html) on how to do this.

Thanks. Entirely new to Github, markdown, and Visual Studio so it may take me some time to get my head around setting up the local environment stuff. I assumed that I had not got everything correct but still hope it is mostly there!

2024-02-05 14:35 UTC, merged